export default {
    'INIT_POSTS': 'INIT_POSTS',
    'CREATE_POST': 'CREATE_POST',
    'FETCH_START_POSTS': 'FETCH_START_POSTS',
    'FETCH_SUCCESS_POSTS': 'FETCH_SUCCESS_POSTS',
    'FETCH_FAILURE_POSTS': 'FETCH_FAILURE_POSTS',

    'CHANGE_POSTS_PAGE': 'CHANGE_POSTS_PAGE',
    'CHANGE_POSTS_SORT': 'CHANGE_POSTS_SORT',

    'FETCH_POST': 'FETCH_POST',
    'FETCH_START_POST': 'FETCH_START_POST',
    'FETCH_SUCCESS_POST': 'FETCH_SUCCESS_POST',
    'FETCH_FAILURE_POST': 'FETCH_FAILURE_POST',
    'SET_EDIT_POST': 'SET_EDIT_POST',
    'CLEAR_EDIT_POST': 'CLEAR_EDIT_POST'
};