export default {
    'INIT_POSTS': 'INIT_POSTS',
    'CREATE_POST': 'CREATE_POST',
    'FETCH_START_POSTS': 'FETCH_START_POSTS',
    'FETCH_SUCCESS_POSTS': 'FETCH_SUCCESS_POSTS',
    'FETCH_FAILURE_POSTS': 'FETCH_FAILURE_POSTS',

    'CHANGE_POSTS_PAGE': 'CHANGE_POSTS_PAGE',
    'CHANGE_POSTS_SORT': 'CHANGE_POSTS_SORT'
};